service: list-sgs

plugins:
  - serverless-plugin-typescript

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-2
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ec2:DescribeRegions
            - ec2:DescribeSecurityGroups
          Resource: '*'

functions:
  getSecurityGroups:
    handler: src/lambda-handlers/get-security-groups.getAllSecurityGroups
    events:
      - http:
          path: security-groups
          method: get
          authorizer:
            name: authorizeRequest
            resultTtlInSeconds: 60
            identitySource: method.request.header.Authorization
            type: token

  authorizeRequest:
    handler: src/authorizers/authorize-request.authorizeRequest
    environment:
      AUTH_TOKEN: ${env:AUTH_TOKEN}
